sudo: required
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
services:
  - xvfb
node_js:
  - "8"
install:
  - npm install
script:
  - npm run lint
