# Copyright (c) 2003-2023, CKSource Holding sp. z o.o.. All rights reserved.
# This file is licensed under the terms of the MIT License (see LICENSE.md).

version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hanghub1
      - hanghub2
      - hanghub3
    ports:
      - "3001:3001"
  redis:
    image: redis
    volumes:
      - ./../data/redis:/data
    restart: always
  hanghub1:
    image: hanghub:latest
  hanghub2:
    image: hanghub:latest
  hanghub3:
    image: hanghub:latest
